---
- name: gather EC2 facts
  hosts: all
  gather_facts: false 

  vars_files:
    - group_vars/all

  tasks:
  - name: gather facts 
    ec2_facts:

- name: terminate hosts
  hosts: tag_Name_demo_{{ tower_user_name }}_windows"
  gather_facts: false

  vars_files:
    - group_vars/all
  vars:
    ec2_hosts: "tag_Name_demo_{{ tower_user_name }}_windows"

  tasks:
  - name: terminate EC2 hosts
    ec2: >
      region="{{ ec2_region }}"
      instance_ids="{{ item }}"
      state=absent
      wait=True
    with_items: "{{hostvars[inventory_hostname]['ansible_ec2_instance_id']}}"

