---
- hosts: localhost
  connection: local
  gather_facts: false 

  vars:
    ec2_region: us-west-2
    ec2_hosts: "tag_Name_demo_{{ tower_user_name }}_windows"

  tasks:
  - name: terminate EC2 hosts
    ec2: >
      region=us-west-2
      instance_ids="{{ item }}"
      state=absent
      wait=True
    with_items: "{{hostvars[inventory_hostname]['ansible_ec2_instance_id']}}"

