---
- name: gather EC2 facts
  hosts: "{{ ec2_hosts }}"
  gather_facts: false 

  tasks:
  - name: gather facts 
    ec2_facts:

- name: terminate hosts
  hosts: "{{ ec2_hosts }}" 
  gather_facts: false
  connection: local  

  tasks:
  - name: terminate EC2 hosts
    ec2:
      region: us-west-2
      instance_tags:
        Name: "demo_{{ tower_user_name }}_windows"
      instance_ids: "{{ item }}"
      state: absent
      wait: True
    with_items: "{{hostvars[inventory_hostname]['ansible_ec2_instance_id']}}"

