---
#Provision some instances:
- hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
  - group_vars/all
  - group_vars/secret.yaml
  - group_vars/windows.yaml
 
  tasks:
  - name: Launch webserver instances
    ec2: >
     access_key="{{ ec2_access_key }}"
     secret_key="{{ ec2_secret_key }}"
     ebs_optimized="true"
     group="{{ ec2_security_group }}"
     type="{{ ec2_instance_type }}"
     image="{{ ec2_windows_image }}"
     region="{{ ec2_region }}"
     instance_tags="{'ansible_group':'windows_webservers', 'type':'{{ ec2_instance_type }}', 'group':'{{ ec2_security_group }}', 'Name':'demo_''{{ tower_user_name }}_windows', 'ansible_set':'windows_demo'}"
     count="{{ ec2_instance_count }}"
     user_data="{{ lookup('template', 'userdata.txt.j2') }}"
     wait=true
    register: ec2

    tags:
      - web

  - name: Launch database instance
    ec2: >
     access_key="{{ ec2_access_key }}"
     secret_key="{{ ec2_secret_key }}"
     ebs_optimized="true"
     group="{{ ec2_security_group }}"
     type="{{ ec2_instance_type }}"
     image="{{ ec2_database_image }}"
     region="{{ ec2_region }}"
     instance_tags="{'ansible_group':'windows_dbservers', 'type':'{{ ec2_instance_type }}', 'group':'{{ ec2_security_group }}', 'Name':'demo_''{{ tower_user_name }}_windows', 'ansible_set':'windows_demo'}"
     count="1"
     user_data="{{ lookup('template', 'userdata.txt.j2') }}"
     wait=true
    register: ec2

    tags:
      - db

  - name: Wait for WinRM to come up
    local_action: wait_for host={{ item.public_dns_name }}
      port=5986 delay=60 timeout=320 state=started
    with_items: "{{ ec2.instances }}"

    tags:
      - web
      - db

